name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./express

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14.x'

    - name: (Express) Install dependencies
      run: ls | npm ci

    - name: (Express) Start server
      run: node index.js

    #- name: Install dependencies and build
    #  run: npm ci
    #- name: Build app
    #  run: npm run build && serve -s build --if-present
    
      # TODO: can add docker image and testing here